params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
stages:
  train:
    cmd: python run_training.py
    deps:
    - run_training.py
artifacts:
  best:
    path: dvclive/artifacts/epoch=4-step=6250.ckpt
    type: model
