training:
  batch_size:
  - 24
  - 24
  batch_size_val: 64
  n_epochs_warmup: 50
  num_workers: 8
  n_epochs: 200
  early_stop_patience: 200
  accumulate_batches: 1
  gradient_clip: 0.0
  median_window: 7
  val_thresholds:
  - 0.5
  n_test_thresholds: 50
  backend: dp
  validation_interval: 1
  seed: 42
  deterministic: false
  precision: 32
  mixup: soft
  obj_metric_strong_type: intersection
  enable_progress_bar: true
  weak_split: 0.9
  consistency_loss: mse
  ema_factor: 0.999
  const_max: 2
scaler:
  statistic: instance
  normtype: minmax
  dims:
  - 1
  - 2
  savepath: ./scaler.ckpt
data:
  synth_folder: 
    /content/drive/MyDrive/DESED_dataset/dcase_synth/audio/train/synthetic21_train/soundscapes_16k/
  synth_tsv: 
    /content/drive/MyDrive/DESED_dataset/dcase_synth/metadata/train/synthetic21_train/soundscapes.tsv
  strong_folder: /content/drive/MyDrive/DESED_dataset/audio/train/strong_label_real_16k/
  strong_tsv: /content/drive/MyDrive/DESED_dataset/metadata/train/audioset_strong.tsv
  weak_folder: /content/drive/MyDrive/DESED_dataset/audio/train/weak_16k/
  weak_tsv: /content/drive/MyDrive/DESED_dataset/metadata/train/weak.tsv
  unlabeled_folder: /content/drive/MyDrive/DESED_dataset/audio/train/unlabel_in_domain_16k/
  unlabeled_tsv: /content/drive/MyDrive/DESED_dataset/metadata/train/unlabel_in_domain.tsv
  synth_val_folder: /content/drive/MyDrive/DESED_dataset/audio/validation/validation_16k/
  synth_val_tsv: /content/drive/MyDrive/DESED_dataset/metadata/validation/validation.tsv
  synth_val_dur: 
    /content/drive/MyDrive/DESED_dataset/metadata/validation/validation_durations.tsv
  test_folder: /content/drive/MyDrive/DESED_dataset/audio/test/public/
  test_tsv: /content/drive/MyDrive/DESED_dataset/metadata/test/public.tsv
  test_dur: /content/drive/MyDrive/DESED_dataset/metadata/test/test_durations.tsv
  eval_folder: /content/drive/MyDrive/DESED_dataset/audio/eval21_16k
  audio_max_len: 10
  fs: 16000
  net_subsample: 1
opt:
  lr: 0.001
feats:
  n_mels: 128
  n_filters: 2048
  hop_length: 256
  n_window: 2048
  sample_rate: 16000
  f_min: 0
  f_max: 8000
net:
  dropout: 0.5
  n_layer_RNN: 2
  n_in_channel: 1
  nclass: 10
  n_RNN_cell: 128
  activation: Relu
  rnn_type: BGRU
  kernel_size:
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  padding:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  stride:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  nb_filters:
  - 16
  - 32
  - 64
  - 128
  - 128
  - 128
  - 128
  pooling:
  - - 1
    - 2
  - - 1
    - 2
  - - 1
    - 2
  - - 1
    - 2
  - - 1
    - 2
  - - 1
    - 2
  - - 1
    - 2
  dropout_recurrent: 0
  attention: true
log_dir: ./exp/
model_name: critical-bond
